export default {
  background: '#F6F8FB',
  backgroundAlt: '#FFFFFF',
  surface: '#FFFFFF',
  primary: '#4a90d9',
  secondary: '#56CCF2',
  border: '#E6ECF5',
  textPrimary: '#1F2937',
  textSecondary: '#64748B',
  placeholder: '#A0AEC0',
  success: '#22C55E',
  error: '#EF4444',
  disabled: '#CBD5E1',
  onPrimary: '#FFFFFF',
  badgeSuccess: '#eaf3de',
  badgeSuccessText: '#3b6d11',
  badgeWarning: '#faeeda',
  badgeWarningText: '#854f0b',
  badgeInfo: '#e6f1fb',
  badgeInfoText: '#185fa5',
  badgeError: '#fcebeb',
  badgeErrorText: '#a32d2d',
  brandNavy: '#0B1E3D',
  brandGold: '#F5C518',
  brandBlue: '#0B57C6',
};